// THIS DOESN'T WORK BECAUSE SERVICE ACCOUNTS DO NOT HAVE STORAGE QUOTA FOR FREE BY DEFAULT
// USE uploadBGLFilesOAUTH isMainThread
// OAUTH UPLOADS FILES AS MY PERSONAL USER WHO HAS ACCESS TO DO SO
// OTHERWISE YOU'LL GET THE FOLLOWING ERROR

// Upload Error: The user's Drive storage quota has been exceeded.



// const fs = require('fs');
// const { google } = require('googleapis');

// // Path to your service account credentials
// const KEYFILEPATH = 'keys.json';
// const SCOPES = ['https://www.googleapis.com/auth/drive.file'];

// const auth = new google.auth.GoogleAuth({
//     keyFile: KEYFILEPATH,
//     scopes: SCOPES,
// });

// async function uploadAndConvert(filePath) {
//     const driveService = google.drive({ version: 'v3', auth });

//     const fileMetadata = {
//         'name': 'Board Game League Results Review',
//         // This specific MIME type triggers the conversion to Google Sheets
//         'mimeType': 'application/vnd.google-apps.spreadsheet',
//         'parents': ['1BcqE7TO46c5oGLTSRp8hPX-bjO7NB1-M']
//     };

//     const media = {
//         mimeType: 'text/csv',
//         body: fs.createReadStream(filePath)
//     };

//     try {
//         const response = await driveService.files.create({
//             resource: fileMetadata,
//             media: media,
//             fields: 'id'
//         });

//         console.log('Success! File uploaded and converted.');
//         console.log('Google Sheet ID:', response.data.id);
//         console.log('Link: https://docs.google.com/spreadsheets/d/' + response.data.id);
//     } catch (err) {
//         console.error('Upload Error:', err.message);
//     }
// }

// // Call with the CSV file generated by your previous script
// uploadAndConvert('./output/BoardGameInsights_HomeLogic.csv');